stages:
  - test
  - name: website
    if: (branch = master) AND (NOT (type IN (push, pull_request)))

jobs:
  include:
    - stage: test
      language: elixir
      elixir: "1.7"
      otp_release: "21.0"
      env:
        - MIX_ENV=test
      script:
        - mix test
        - mix credo --ignore-checks Design
    - stage: website
      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
